services:
  glasses-postgres:
    image: postgres:16
    container_name: glasses-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ordersdb
    volumes:
      - glasses-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    

  bot:
    build: .
    container_name: glasses-bot
    depends_on:
      glasses-postgres:
        condition: service_healthy
    env_file:
      - .env
    restart: always

volumes:
  glasses-postgres-data:

